### PR TITLE
Upgrades to the latest server and adds function to upload ksql-files

### PR DESCRIPTION
**Pull request by maulikjs**
Changed all the defaults to JSON since the next step in their pipeline is multi level JSONS
Added checks to see server health before running queries
Added class to instantiate a server pointer and upload a .ksql file
Conform to pep8

### CODE REVIEW

**Comment by maulikjs** [comment]
@bryanyang0528 hey bryan
as requested.

**Comment by bryanyang0528** [comment]
Ok Thanks. I'll test and add test cases for it.

**Comment by maulikjs** [comment]
Ok awesome @bryanyang0528 do let me know if any changes are required. You do have my email. Ill tend to it at the earliest.

**Comment by bryanyang0528** [comment]
no problem

**Pull request merged**
