### PR TITLE
Migrate to KSQL stable version 4.1.0 

### PR DESCRIPTION
**Pull request by sebastianneubauer**
- all tests are running with version 4.1.0
- updated docker-compose file to setup proper ksql-server version 4.1.0

- breaking change: server versions below the stable 4.1.0 are not fully supported any more:
 - only `get_ksql_version` doesn't work anymore, all the rest should work the same

### CODE REVIEW

**Comment by sebastianneubauer** [comment]
Anything I can do to move this forward? In the meanwhile ksql 5.x beta is out and it will bring the next set of breaking changes...

**Comment by maulikjs** [comment]
@bryanyang0528 the stuff i worked on in the branch uploadfiles works perfectly fine with version 5.x beta
and I will be working on it once it actually comes out. Can you help me out with how you want the tests written for it? Maybe I can get those done too.

**Comment by sebastianneubauer** [comment]
@maulikjs I don't really understand, where are you working on? Is it related with this PR? Maybe I can help you with the tests?

**Comment by bryanyang0528** [comment]
@sebastianneubauer @maulikjs  Thanks for contribution and sorry for late reply. I'll merge @maulikjs 's uploadfiles version first and see if any conflicts.

**Pull request merged**
