### PR TITLE
Migration to ksql 5.x

### PR DESCRIPTION
**Pull request by sebastianneubauer**
This PR is admittedly very big, it is my proposal for a migration to ksql 5.0 which brings some major changes:

- API responses changed in structure
- error handling changes significantly, but in the current beta it still seems to have some rough edges
- the docker images changed a bit, it is now recommended to use the hosts network, I am not super happy with it, but that is how I got it working for now

This PR breaks compatibility with ksql<5.0, it can be done in a backwards compatible way, but that is significant effort which has to be carefully checked if it is worth

In order to improve the tests robustness I introduced a whole set of handy utilities, mainly for deleting streams. They are currently separated, but could also be included in the client class.

### CODE REVIEW

**Comment by sebastianneubauer** [comment]
If there are positive signals that this PR can be merged, I will of course add tests such that line coverage is improved compared to master.

**Comment by sebastianneubauer** [comment]
But watch out, it breaks compatibility to all versions except the beta 5.x (so no current stable version supported) , so don't be too quick😉

**Comment by bryanyang0528** [comment]
@sebastianneubauer  Thanks! I'll keep this PR until stable version released.

**Comment by maulikjs** [comment]
They recently came out with version 5.1.x. Which supports nested JSON (and other formats) which is a game change! Should we start migrating to it? 
I was recently working on another project and could circle back and try and get this done or do we wanna wait for a stable release?

**Comment by sebastianneubauer** [comment]
@maulikjs where have you seen 5.1.x? At least on dockerhub, they only have prebuilds for 5.0...

**Comment by maulikjs** [comment]
In the preview release that came out last month. I have a docker image
pushed to
Quay.io/mshah/ksqlserver:5.1.0-Snapshot

I'm currently working on getting the jmx metrics out of the server cause
that would a great feature to have for monitoring purposes.

**Comment by sebastianneubauer** [comment]
mmmh, could it be, that 5.1.0-snapshot is identical to the 5.0 release version? At least that is what I would deduce from the recent releases: https://github.com/confluentinc/ksql/releases

**Comment by sebastianneubauer** [comment]
ah, no you are right, I overlooked the v5.1.0-beta180724024536 release. 🤔

**Comment by sebastianneubauer** [comment]
Ok, this got a little bit bigger:
* migrated to 5.0
* added some utilities to make testing easier
* query now has a "idle_timeout", so after x seconds of not receiving any more data from the stream, the query returns. This was needed for testing.

Happy to discuss, but from my side it is finished so far!

**Comment by kaiwaehner** [comment]
Happy to see this migration. 

Looking forward to use this Client together with KSQL 5 as soons as it is merged and working.

**Comment by kaiwaehner** [comment]
This migration is not finished / merged yet, right? (sorry, I don't use Github or coding in general on a daily basis) :-)

I assume the best way is to monitor this PR and see when it is finally merged?

**Comment by sebastianneubauer** [comment]
@bryanyang0528 is there anything I can do to speed up the merge? From my side there are no open issues, do you have any?

**Comment by sebastianneubauer** [comment]
@bryanyang0528 Could you remove the WIP label, it is no work in progress anymore

**Comment by bryanyang0528** [comment]
Sorry for late reply. `stream_properties` is awesome and useful.

**Comment by sebastianneubauer** [comment]
Yes, the only thing might be to add a changelog or even migration how to (there are some breaking changes), this could be done once it is merged together with all other changes, before the next release.

**Comment by bryanyang0528** [comment]
No problem. Thank you.

**Comment by bryanyang0528** [comment]
resolved #39

**Pull request merged**
