### PR TITLE
Support new query-stream API with HTTP/2

### PR DESCRIPTION
**Pull request by harlev**
Added optional support for the new HTTP/2 endpoint for queries, requested in https://github.com/bryanyang0528/ksql-python/issues/77

This is a non breaking change. The new endpoint will only be used when `use_http2=True` is passed into `Query` in the client.

Since it looks like Python's `requests` does not support HTTP/2, added the [Hyper](https://hyper.readthedocs.io/) package.

The test for Query was enhanced to test both HTTP/1.1 and HTTP/2 with the `/query` and `/query-stream` endpoints receptively

### CODE REVIEW

**Comment by harlev** [comment]
In a later PR there should be support for the other [new endpoints](https://docs.ksqldb.io/en/latest/developer-guide/ksqldb-rest-api/streaming-endpoint/)

- /close-query
- /inserts-stream

**Comment by bryanyang0528** [comment]
@harlev that's great. Let met know if you complete this cool feature.

**Comment by harlev** [comment]
@bryanyang0528 last two APIs are implemented

**Comment by bryanyang0528** [comment]
@harlev I merged #78 but some conflict happened. Would you mind helping resolve the conflict and push again?

**Comment by bryanyang0528** [comment]
@harlev  Thanks for your contribution. Nice implementation.

**Pull request merged**
